import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Example manual Sidebar (if we ever decide to do that):
  // knowledgeBase: [
  //   {
  //     type: 'category',
  //     label: 'Knowledge Base',
  //     // TODO: Add pages under the knowledge base
  //     items: [
  //       {
  //         'VPNs': [
  //           'knowledge-base/VPNs/Introduction',
  //           'knowledge-base/VPNs/VPN Setup'
  //          ]
  //       }
  //     ],
  //   },
  // ],
   
};

export default sidebars;